routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GstController;
use App\Http\Controllers\VidioController;
use App\Http\Controllers\PropertyController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\OpenHouseController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home.home');
});
Route::get('/', [HomeController::class, 'index'])->name('home');
//Route::get('/home', [HomeController::class, 'index'])->name('home');

//GST
Route::middleware(['auth:sanctum', 'verified'])->get('/gst', function () {
    return view('pages/gst/index');
})->name('gst');
Route::middleware(['auth:sanctum', 'verified'])->get('/gst/report', function () {
    return view('pages/gst/report');
})->name('gst/report');
Route::get('/gst', [GstController::class, 'index'])->name('gst');
Route::get('/gst/single_vidio/{id}', [GstController::class, 'singleVidio'])->name('gst/single_vidio');
Route::post('/gst/updateReport', [GstController::class, 'updateReport'])->name('update_report_gst');
Route::get('/gst/getAgentReport', [GstController::class, 'getAgentReport'])->name('gst/getAgentReport');
Route::get('/gst/getVidioReport', [GstController::class, 'getVidioReport'])->name('gst/getVidioReport');
Route::get('/gst/getStatistic', [GstController::class, 'getStatistic'])->name('gst/getStatistic');
Route::get('/gst/detail_agent/{id}', [GstController::class, 'detailAgent'])->name('gst/detail_agent');
Route::get('/gst/detail_vidio/{id}', [GstController::class, 'detailVidio'])->name('gst/detail_vidio');


//PROPERTY
Route::get('/property', [PropertyController::class, 'index'])->name('property');
Route::get('/property/getCity', [PropertyController::class, 'getCity'])->name('property/getCity');
Route::get('/property/getProvince', [PropertyController::class, 'getProvince'])->name('property/getProvince');
Route::get('/property/getPropertyPDF', [PropertyController::class, 'createPDF'])->name('property/getPropertyPDF');
Route::get('/property/getPropertyAPI', [PropertyController::class, 'getPropertyAPI'])->name('property/getPropertyAPI');



//VIDIO
Route::resource('vidios', VidioController::class);

//OPEN HOUSE
Route::get('/open-house', [OpenHouseController::class, 'index'])->name('open-house');
Route::get('/open-house-galaxy/{id}', [OpenHouseController::class, 'getByRegion'])->name('open-house-galaxy');
Route::get('/open-house/city/{id}', [OpenHouseController::class, 'getByProvince'])->name('open-house/city');
Route::get('/open-house/create', [OpenHouseController::class, 'create'])->name('open-house/create');
Route::get('/open-house/list-property', [OpenHouseController::class, 'listProperty'])->name('open-house/list-property');
Route::post('/open-house/destroy/{id}', [OpenHouseController::class, 'destroy'])->name('open-house/destroy');
Route::get('/open-house/store/{id}', [OpenHouseController::class, 'store'])->name('open-house/store');
Route::get('/open-house/cetak-listing', [OpenHouseController::class, 'cetakListing'])->name('open-house/cetak-listing');
Route::get('/open-house/export/{id}', [OpenHouseController::class, 'export'])->name('open-house/export');

//EMAIL
Route::get('/home/sendEmail', [HomeController::class, 'sendEmail'])->name('home/sendEmail');

//WISHLIST
//Route::resource('wishlist', WishlistController::class);
Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist');
Route::get('/wishlist/create', [WishlistController::class, 'create'])->name('wishlist/create');
Route::post('/wishlist/destroy/{id}', [WishlistController::class, 'destroy'])->name('wishlist/destroy');
Route::post('/wishlist/store', [WishlistController::class, 'store'])->name('wishlist/store');
Route::post('/wishlist/update', [WishlistController::class, 'update'])->name('wishlist/update');
Route::get('/wishlist/edit/{id}', [WishlistController::class, 'edit'])->name('wishlist/edit');
Route::get('/wishlist/addToWishlist', [WishlistController::class, 'addToWishlist'])->name('wishlist/addToWishlist');
Route::get('/wishlist/addToWishlistModal', [WishlistController::class, 'addToWishlistModal'])->name('wishlist/addToWishlistModal');

app/Models/Vidio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vidio extends BaseModel
{
    use HasFactory;

    protected $table = 'vidios';
    public $timestamps = true;

    protected $fillable = [
        'name',
        'code',
        'duration',
        'link_url',
        'order'
    ];
}

app/Http/Controllers/VidioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Vidio;
use Illuminate\Http\Request;
use App\Models\ReportGst;

class VidioController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vidios = Vidio::latest()->paginate(5);

        return view('pages.vidios.index', compact('vidios'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.vidios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $link = $request->input('link_url');
        // substr($link,strpos($mystring, '/'),);
        $stat = false;
        $code = "";
        for ($i=0; $i < strlen($link) ; $i++) { 
            if ($link[$i]=='=') {
                $stat = true;
                continue;
            }
            if ($link[$i]=='&') {
                $stat = false;
                break;
            }
            if ($stat) {
                $code.=$link[$i];
            }
        }
        $request->validate([
            'name' => 'required',
            'duration' => 'required',
            'link_url' => 'required'
        ]);
        $vidio['name'] = $request->input('name');
        $vidio['duration'] = $request->input('duration');
        $vidio['link_url'] = $link;
        $vidio['code'] = $code;
        Vidio::create($vidio);

        return redirect()->route('vidios.index')
            ->with('success', 'Vidio created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Vidio  $vidio
     * @return \Illuminate\Http\Response
     */
    public function show(Vidio $vidio)
    {
        return view('pages.vidios.show', compact('vidio'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Vidio  $vidio
     * @return \Illuminate\Http\Response
     */
    public function edit(Vidio $vidio)
    {
        return view('pages.vidios.edit', compact('vidio'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Vidio  $vidio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vidio $vidio)
    {
        $link = $request->input('link_url');
        // substr($link,strpos($mystring, '/'),);
        $stat = false;
        $code = "";
        for ($i=0; $i < strlen($link) ; $i++) { 
            if ($link[$i]=='=') {
                $stat = true;
                continue;
            }
            if ($link[$i]=='&') {
                $stat = false;
                break;
            }
            if ($stat) {
                $code.=$link[$i];
            }
        }
        $request->validate([
            'name' => 'required',
            'duration' => 'required',
            'link_url' => 'required'
        ]);
        $vidion['name'] = $request->input('name');
        $vidion['duration'] = $request->input('duration');
        $vidion['link_url'] = $link;
        $vidion['code'] = $code;

        $vidio->update($vidion);

        return redirect()->route('vidios.index')
            ->with('success', 'Vidio updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Vidio  $vidio
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vidio $vidio)
    {
        $report = ReportGst::where('vidio_id',$vidio->id)->get();
        foreach ($report as $key => $value) {
            $value->delete();
        }
        $vidio->delete();
        return redirect()->route('vidios.index')
                        ->with('success','Vidio deleted successfully');
    }

}

resources/views/pages/vidios/create.blade.php
@extends('layouts.app')
@section('content')

<div class="site-section site-section-sm" style="background-color: #808080;">

</div>
<div class="row"  style="margin: 2em;">
    <div class="row" style="margin: 2em;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Vidio</h2>
            </div>
            <br>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('vidios.store') }}" method="POST" >
        @csrf

        <div class="row" style="margin: 2em;">
            <input id="id" class="form-control col-md-12 col-xs-12" name="id" type="hidden" value="{{@$vidio->id}}">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name" required="required" value="{{@$vidio->name}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Duration:</strong>
                    <input type="text" name="duration" class="form-control" placeholder="duration" required="required" value="{{@$vidio->duration}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Url Link:</strong>
                    <textarea class="form-control" style="height:50px" name="link_url"
                        placeholder="link"></textarea>
                </div>
            </div>
            <input class="form-control col-md-12 col-xs-12" name="is_active" type="hidden" value="{{@$vidio->is_active}}">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>
@endsection

resources/views/pages/vidios/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="site-section site-section-sm" style="background-color: #808080;">

</div>
<div class="row"  style="margin: 2em;">
    <div class="row" style="margin: 2em;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Vidio</h2>
            </div>
            <br>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('vidios.update',$vidio->id) }}" method="POST" >
        @csrf
        @method('PUT')

        <div class="row" style="margin: 2em;">
            <input id="id" class="form-control col-md-12 col-xs-12" name="id" type="hidden" value="{{@$vidio->id}}">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name" required="required" value="{{@$vidio->name}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Duration:</strong>
                    <input type="text" name="duration" class="form-control" placeholder="duration" required="required" value="{{@$vidio->duration}}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Url Link:</strong>
                    <textarea class="form-control" style="height:50px" name="link_url"
                        placeholder="link">{{@$vidio->link_url}}</textarea>
                </div>
            </div>
            <input class="form-control col-md-12 col-xs-12" name="is_active" type="hidden" value="{{@$vidio->is_active}}">
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</div>
@endsection

resources/views/pages/vidios/index.blade.php
@extends('layouts.app')
@section('content')
<div class="ftco-blocks-cover-1">
      <div class="site-section overlay site-section-sm" data-stellar-background-ratio="0.5" style="background-image: url('{{asset('images/Foto-Galaxy-desktop.jpg')}}')">
        <div class="container">
          <div class="row align-items-center justify-content-center text-center">
          </div>
        </div>
      </div>
    </div>
<div class="row" style="margin: 1em;">
    <div class="row" style="margin: 2em;">
        <p><a href="{{ route('vidios.create') }}" style="background-color: #c10016;" class="btn btn-primary text-white px-4 py-3">Add Vidio</a></p>
    </div>
    @if ($message = Session::get('success'))
    <div class="row" style="margin: 1em;" style="width: 100%;">
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    </div>   
        
    @endif
    <div class="row" style="margin: 2em; overflow-x:auto;">
    <table id="mytable" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Duration</th>
                <th>Link Url</th>
                <th width="20%">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($vidios as $vidio)
            <tr>
                <td>{{ $vidio->code}}</td>
                <td>{{ $vidio->name }}</td>
                <td>{{ $vidio->duration }}</td>
                <td><a target="blank" href="{{ $vidio->link_url }}">{{ $vidio->link_url }}</a></td>
                <td >
                    <form action="{{ route('vidios.destroy', $vidio->id) }}" method="POST">

                        <a href="{{ route('vidios.edit', $vidio->id) }}" title="show" class="btn btn-primary text-white px-2 py-1">
                            <i class="fa fa-edit"></i>
                        </a>

                        @csrf
                        @method('DELETE')
                        <button id="testform" type="submit" title="delete" class="btn btn-primary text-white px-2 py-1">
                            <i class="fa fa-trash-o"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div>
</div>
@endsection
@section('js_extras')
<script type="text/javascript">
$(document).ready(function(){
  $("#mytable").DataTable();

  $("#testform").click(function(event) {
      var hasil = confirm("Apakah anda yakin untuk menghapus vidio ini ?");
      if (!hasil) {
        event.preventDefault();
      }
    });
});
</script>
@endsection