routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\GstController;
use App\Http\Controllers\VidioController;
use App\Http\Controllers\PropertyController;
use App\Http\Controllers\WishlistController;
use App\Http\Controllers\OpenHouseController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages.home.home');
});
Route::get('/', [HomeController::class, 'index'])->name('home');
//Route::get('/home', [HomeController::class, 'index'])->name('home');

//GST
Route::middleware(['auth:sanctum', 'verified'])->get('/gst', function () {
    return view('pages/gst/index');
})->name('gst');
Route::middleware(['auth:sanctum', 'verified'])->get('/gst/report', function () {
    return view('pages/gst/report');
})->name('gst/report');
Route::get('/gst', [GstController::class, 'index'])->name('gst');
Route::get('/gst/single_vidio/{id}', [GstController::class, 'singleVidio'])->name('gst/single_vidio');
Route::post('/gst/updateReport', [GstController::class, 'updateReport'])->name('update_report_gst');
Route::get('/gst/getAgentReport', [GstController::class, 'getAgentReport'])->name('gst/getAgentReport');
Route::get('/gst/getVidioReport', [GstController::class, 'getVidioReport'])->name('gst/getVidioReport');
Route::get('/gst/getStatistic', [GstController::class, 'getStatistic'])->name('gst/getStatistic');
Route::get('/gst/detail_agent/{id}', [GstController::class, 'detailAgent'])->name('gst/detail_agent');
Route::get('/gst/detail_vidio/{id}', [GstController::class, 'detailVidio'])->name('gst/detail_vidio');


//PROPERTY
Route::get('/property', [PropertyController::class, 'index'])->name('property');
Route::get('/property/getCity', [PropertyController::class, 'getCity'])->name('property/getCity');
Route::get('/property/getProvince', [PropertyController::class, 'getProvince'])->name('property/getProvince');
Route::get('/property/getPropertyPDF', [PropertyController::class, 'createPDF'])->name('property/getPropertyPDF');
Route::get('/property/getPropertyAPI', [PropertyController::class, 'getPropertyAPI'])->name('property/getPropertyAPI');



//VIDIO
Route::resource('vidios', VidioController::class);

//OPEN HOUSE
Route::get('/open-house', [OpenHouseController::class, 'index'])->name('open-house');
Route::get('/open-house-galaxy/{id}', [OpenHouseController::class, 'getByRegion'])->name('open-house-galaxy');
Route::get('/open-house/city/{id}', [OpenHouseController::class, 'getByProvince'])->name('open-house/city');
Route::get('/open-house/create', [OpenHouseController::class, 'create'])->name('open-house/create');
Route::get('/open-house/list-property', [OpenHouseController::class, 'listProperty'])->name('open-house/list-property');
Route::post('/open-house/destroy/{id}', [OpenHouseController::class, 'destroy'])->name('open-house/destroy');
Route::get('/open-house/store/{id}', [OpenHouseController::class, 'store'])->name('open-house/store');
Route::get('/open-house/cetak-listing', [OpenHouseController::class, 'cetakListing'])->name('open-house/cetak-listing');
Route::get('/open-house/export/{id}', [OpenHouseController::class, 'export'])->name('open-house/export');

//EMAIL
Route::get('/home/sendEmail', [HomeController::class, 'sendEmail'])->name('home/sendEmail');

//WISHLIST
//Route::resource('wishlist', WishlistController::class);
Route::get('/wishlist', [WishlistController::class, 'index'])->name('wishlist');
Route::get('/wishlist/create', [WishlistController::class, 'create'])->name('wishlist/create');
Route::post('/wishlist/destroy/{id}', [WishlistController::class, 'destroy'])->name('wishlist/destroy');
Route::post('/wishlist/store', [WishlistController::class, 'store'])->name('wishlist/store');
Route::post('/wishlist/update', [WishlistController::class, 'update'])->name('wishlist/update');
Route::get('/wishlist/edit/{id}', [WishlistController::class, 'edit'])->name('wishlist/edit');
Route::get('/wishlist/addToWishlist', [WishlistController::class, 'addToWishlist'])->name('wishlist/addToWishlist');
Route::get('/wishlist/addToWishlistModal', [WishlistController::class, 'addToWishlistModal'])->name('wishlist/addToWishlistModal');

resources/views/pages/includes/footer.blade.php
<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h3 class="text-white h5 mb-3">Subscribe</h3>
            <form action="" class="d-flex">
              <input type="text" class="form-control mr-3" placeholder="Enter your email">
              <input style="background-color: #c10016;" type="submit" class="btn btn-danger text-white" value="Send Now">
            </form>
          </div>
          <div class="col-md-3 ml-auto">
            <h3 class="text-white h5 mb-3">Connect With Us</h3>
            <ul class="list-unstyled menu-arrow">
             
<!--[if mso]></td></tr></table><![endif]-->
<table cellpadding="0" cellspacing="0" class="social_icons" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" valign="top" width="100%">
<tbody>
<tr style="vertical-align: top;" valign="top">
<td style="word-break: break-word; vertical-align: top; padding-top: 10px; padding-right: 10px; padding-bottom: 10px; padding-left: 10px;" valign="top">
<table align="center" cellpadding="0" cellspacing="0" class="social_table" role="presentation" style="table-layout: fixed; vertical-align: top; border-spacing: 0; border-collapse: collapse; mso-table-tspace: 0; mso-table-rspace: 0; mso-table-bspace: 0; mso-table-lspace: 0;" valign="top">
<tbody>
<tr align="center" style="vertical-align: top; display: inline-block; text-align: center;" valign="top">
<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 2.5px; padding-left: 2.5px;" valign="top"><a href="https://www.facebook.com/id.galaxyproperty/" target="_blank"><img alt="Facebook" height="32" src="images/facebook2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="facebook" width="32"/></a></td>
<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 2.5px; padding-left: 2.5px;" valign="top"><a href="https://twitter.com/galaxy_property" target="_blank"><img alt="Twitter" height="32" src="images/twitter2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="twitter" width="32"/></a></td>
<td style="word-break: break-word; vertical-align: top; padding-bottom: 0; padding-right: 2.5px; padding-left: 2.5px;" valign="top"><a href="https://www.instagram.com/galaxy.property/" target="_blank"><img alt="Instagram" height="32" src="images/instagram2x.png" style="text-decoration: none; -ms-interpolation-mode: bicubic; height: auto; border: 0; display: block;" title="instagram" width="32"/></a></td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
            </ul>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>
    

resources/views/pages/includes/header.blade.php
<header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">
            <div class="col-3 ">
                <img src="{{asset('images/galaxy_logo_red.png')}}" style="width: 130px; height: 40px;">
            </div>

            <div class="col-9  text-right">
              <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>

              

              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li><a href="{{ route('home')}}" class="nav-link">Home</a></li>
                  <li><a href="{{ route('property')}}" class="nav-link">Property</a></li>
                  @if (Auth::check())
                  @else
                  <li><a href="{{ route('open-house')}}" class="nav-link">Open House</a></li>
                  @endif
                  @if (Auth::check())
                  <li><a href="{{ route('wishlist')}}" class="nav-link">My Wishlist</a></li>
                  @if(Auth::user()->is_admin)
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      GST Manager
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style=" background-color: white;">
                      <a class="dropdown-item" href="{{ route('gst')}}" class="nav-link">GST</a>
                      <a class="dropdown-item" href="{{ route('vidios.index')}}">List Vidio</a>
                      <a class="dropdown-item" href="{{ route('gst/report')}}">Report GST</a>
                    </div>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Open House Manager
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown" style=" background-color: white;">
                      <a href="{{ route('open-house')}}" class="dropdown-item">Open House</a>
                      <a href="{{ route('open-house/create')}}" class="dropdown-item">List All Property</a>
                      <a href="{{ route('open-house/list-property')}}" class="dropdown-item">List Property Open House</a>
                      <a href="{{ route('open-house/cetak-listing')}}" class="dropdown-item">Cetak Listing</a>
                    </div>
                  </li>
                  @else
                  <li><a href="{{ route('gst')}}" class="nav-link">GST</a></li>
                  @endif
                  <li>
                    <li>
                    <form method="POST" action="{{ route('logout') }}">
                              @csrf

                              <x-jet-dropdown-link style="color: #c10016;" href="{{ route('logout') }}"
                                                      onclick="event.preventDefault();
                                                                  this.closest('form').submit();">
                                      {{ __('Logout') }}
                                  </x-jet-dropdown-link>
                              </form>
                  </li>
                  @else
                  <li><a href="{{ route('login') }}" class="nav-link">Login</a></li>
                  @endif
                  
                </ul>
              </nav>
            </div>

            
          </div>
        </div>

      </header>

resources/views/pages/includes/news_post.blade.php
 <div class="site-section bg-light">
      <div class="container">

        <div class="row justify-content-center mb-5">
          <div class="col-md-6 text-center">
            <h3 class="heading-29201 text-center">Blog Posts</h3>
            
            <p class="mb-5">Perspiciatis quidem, harum provident, repellat sint officia quos fugit tempora id deleniti.</p>
          </div>
        </div>

        <div class="row">
          
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="single.html">
                <img src="images/img_1.jpg" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="single.html">Lorem ipsum dolor sit amet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="single.html">
                <img src="images/img_2.jpg" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="single.html">Lorem ipsum dolor sit amet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="post-entry-1 h-100">
              <a href="single.html">
                <img src="images/img_3.jpg" alt="Image"
                 class="img-fluid">
              </a>
              <div class="post-entry-1-contents">
                
                <h2><a href="single.html">Lorem ipsum dolor sit amet</a></h2>
                <span class="meta d-inline-block mb-3">July 17, 2019 <span class="mx-2">by</span> <a href="#">Admin</a></span>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores eos soluta, dolore harum molestias consectetur.</p>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>